[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"
[project]
name = "rsnapshot-docker-compose-backup"
dynamic = ["version"]
authors = [
  { name = "Christoph Wildhagen", email = "git@christoph-wildhagen.de" },
]
description = "A config generator for rsnapshot"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]
[project.scripts]
rsnapshot-docker-compose-backup = "rsnapshot_docker_compose_backup.backup_planer:main"
[project.urls]
Homepage = "https://github.com/d3kad3nt/rsnapshot-docker-compose-backup"
Issues = "https://github.com/d3kad3nt/rsnapshot-docker-compose-backup/issues"
[tool.hatch.version]
source = "versioningit"
[tool.hatch.envs.default]
python = "3.10"
dependencies = ["mypy", "pytest", "pylint"]
[tool.hatch.envs.hatch-static-analysis]
config-path = "ruff_defaults.toml"
dependencies = ["black", "isort", "ruff", "flake8"]
[tool.hatch.envs.hatch-static-analysis.scripts]
format-check = [
  "black --check --diff -t py310 {args:.}",
  "isort --check-only --diff {args:.}",
]
format-fix = ["isort {args:.}", "black -t py310 {args:.}"]
lint-check = ["ruff check {args:.}", "flake8 {args:.}"]
lint-fix = ["ruff check --fix {args:.}", "lint-check"]
[tool.ruff]
extend = "ruff_defaults.toml"
[tool.isort]
profile = "black"
