# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          # Use version of Hatch that is on my machine
          version: "1.16.4"
      - name: check for linter errors
        run: hatch fmt --check --linter
  format:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          # Use version of Hatch that is on my machine
          version: "1.16.4"
      - name: check for formatter errors
        run: hatch fmt --check --formatter
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install Hatch
        uses: pypa/hatch@install
        with:
          # Use version of Hatch that is on my machine
          version: "1.16.4"
      - name: Run unit tests
        run: hatch test --python ${{ matrix.python-version }} tests/unit/
